### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by PandaWannaSleep** [tawnysky/PLIN#2]
Hi, I'm currently reading your code, and I'm confused about the func "find_leaf_node" in inner_node.h.
At line 93, when searching left, why it doesn't consider the situation that key still smaller than the slot's min_key after --slot.
Your code is:
```
if (inner_slots[slot].min_key == FREE_FLAG || key < inner_slots[slot].min_key) {
  while (inner_slots[--slot].min_key == FREE_FLAG) {}
}
```
How about writing like this:
```
if (inner_slots[slot].min_key == FREE_FLAG || key < inner_slots[slot].min_key) {
  while (inner_slots[--slot].min_key == FREE_FLAG) {}
  while(key < inner_slots[slot].min_key) { slot--; }
}
```
Could you give me some advice?
Thanks a lot.

**Comment by tawnysky** [comment]
Thank you very much for your advice. After checking, I think the implementation here is correct.
When inserting inside an inner node, we always have the leaf nodes in a block in order, with all the empty slots in each block to the right of the block. Our search process is based on this assumption, so it's guaranteed to be correct.

**Comment by PandaWannaSleep** [comment]
I appreciate your patient explanation, thanks a lot.
